# Stage 1: Build Stage
FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Production Stage
FROM node:22-alpine

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/package.json /usr/src/app/package-lock.json ./
RUN npm install --only=production

COPY --from=build /usr/src/app/dist ./dist

EXPOSE 3500

# Define the command to start the application
CMD ["npm", "start"]