name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH to connect to the Droplet
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Add Droplet to known_hosts
    - name: Add Droplet to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    # Step 4: Copy files to the Droplet
    - name: Copy files to server
      run: |
        scp -r ./* root@${{ secrets.DROPLET_IP }}:/home/root/app

    # Step 5: SSH into the Droplet and deploy
    - name: Deploy on server
      run: |
        ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/root/app
          docker-compose down
          docker-compose up -d --build
        EOF