name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH to connect to the Droplet
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Add Droplet to known_hosts
    - name: Add Droplet to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    # Step 4: Ensure the target directory exists
    - name: Create target directory
      run: |
        ssh root@${{ secrets.DROPLET_IP }} "mkdir -p /home/root/app"

    # Step 5: Copy files to the Droplet
    - name: Copy files to server
      run: |
        scp -r ./* root@${{ secrets.DROPLET_IP }}:/home/root/app

    # Step 5.1: Debug secrets safely
    - name: Debug secrets
      run: |
        if [ -z "${{ secrets.FRONTEND_ENV }}" ]; then
          echo "Error: FRONTEND_ENV is empty or not set!" && exit 1
        else
          echo "FRONTEND_ENV is set and has $(echo -n "${{ secrets.FRONTEND_ENV }}" | wc -c) characters."
        fi

        if [ -z "${{ secrets.API_ENV }}" ]; then
          echo "Error: API_ENV is empty or not set!" && exit 1
        else
          echo "API_ENV is set and has $(echo -n "${{ secrets.API_ENV }}" | wc -c) characters."
        fi

        if [ -z "${{ secrets.STORAGE_ENV }}" ]; then
          echo "Error: STORAGE_ENV is empty or not set!" && exit 1
        else
          echo "STORAGE_ENV is set and has $(echo -n "${{ secrets.STORAGE_ENV }}" | wc -c) characters."
        fi

    # Step 5.2: Create .env files on server
    - name: Create .env files on server
      run: |
        ssh root@${{ secrets.DROPLET_IP }} "printf '%s\n' '${{ secrets.FRONTEND_ENV }}' > /home/root/app/flashback-front-end/.env"
        ssh root@${{ secrets.DROPLET_IP }} "printf '%s\n' '${{ secrets.API_ENV }}' > /home/root/app/flashback-api/.env"
        ssh root@${{ secrets.DROPLET_IP }} "printf '%s\n' '${{ secrets.STORAGE_ENV }}' > /home/root/app/storage-service/.env"
        
    # Step 6: SSH into the Droplet and deploy
    - name: Deploy on server
      run: |
        ssh root@${{ secrets.DROPLET_IP }} "cd /home/root/app && docker compose down && docker compose up -d --build"